name: kpa_erp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # It's good practice to define a range

dependencies:
  flutter:
    sdk: flutter
  
  android_intent_plus: ^5.3.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dart_jsonwebtoken: ^3.2.0
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  gap: ^3.0.1
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1 # Using a consistent version from your overrides
  local_auth: ^2.3.0
  multi_dropdown: ^3.0.1
  open_filex: ^4.7.0
  package_info_plus: ^8.0.0 # Added package_info_plus from previous error
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  workmanager: ^0.8.0
  http: ^1.1.0 # Added http from your overrides

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true

  # --- THE FIX IS HERE ---
  # By adding a trailing slash to the directory path, you are telling Flutter
  # to include all the files inside the 'assets/images/' folder.
  assets:
    - assets/images/

# It seems you had some dependency overrides, which is fine.
# I've moved them into the main dependencies list for clarity.
# If you need specific overrides, you can keep the override section.
# dependency_overrides:
#   http: ^1.1.0
#   meta: ^1.11.0
#   intl: ^0.18.1

