// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DiO4NZoyqRptm-fccQkkjz62mUugZGM',
    appId: '1:415810021220:web:e3bd5097b20da36fa77c71',
    messagingSenderId: '415810021220',
    projectId: 'kpa-erp-assignment-ff685',
    authDomain: 'kpa-erp-assignment-ff685.firebaseapp.com',
    storageBucket: 'kpa-erp-assignment-ff685.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuryWO0SaleVGt-w-a2nJ8KMwkXClUuhw',
    appId: '1:415810021220:android:104f9fedbe8b51a5a77c71',
    messagingSenderId: '415810021220',
    projectId: 'kpa-erp-assignment-ff685',
    storageBucket: 'kpa-erp-assignment-ff685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfDUUpnRCoPpgTbb6vaDeXPdKqfxEaeg',
    appId: '1:415810021220:ios:8f9e0d303f29cd08a77c71',
    messagingSenderId: '415810021220',
    projectId: 'kpa-erp-assignment-ff685',
    storageBucket: 'kpa-erp-assignment-ff685.firebasestorage.app',
    iosBundleId: 'com.example.kpaErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DiO4NZoyqRptm-fccQkkjz62mUugZGM',
    appId: '1:415810021220:web:45741a9cc50587faa77c71',
    messagingSenderId: '415810021220',
    projectId: 'kpa-erp-assignment-ff685',
    authDomain: 'kpa-erp-assignment-ff685.firebaseapp.com',
    storageBucket: 'kpa-erp-assignment-ff685.firebasestorage.app',
  );
}
